### ISSUE TITLE
Use as a sort function?

### ISSUE THREAD

**Issue by M-Gonzalo** [dsablic/node-nilsimsa#8]
Can this be used to sort lists of data?  Is it just a matter of using `compare` as the comparison function?

**Comment by dsablic** [comment]
If your goal is similarity search, then [Vantage-point trees](https://en.wikipedia.org/wiki/Vantage-point_tree) with the Hamming distance metric is a good option. For a fairly small collection of hashes, you could just calculate distance between the input hash and all of the hashes in collection to filter out the ones that are not within your similarity criteria (distance).

**Comment by M-Gonzalo** [comment]
> If your goal is similarity search, then [Vantage-point trees](https://en.wikipedia.org/wiki/Vantage-point_tree) with the Hamming distance metric is a good option. For a fairly small collection of hashes, you could just calculate distance between the input hash and all of the hashes in collection to filter out the ones that are not within your similarity criteria (distance).

Yeah, I realized too late it was a dumb question. My brute-force-ish solution, for now, is to start with the biggest file, calculate the difference with all the rest, and pick the closest to continue. It's slower at first, picking up speed as it advances the loop bc there are fewer and fewer elements to compare

I'll take a look at your link later today.

Thanks for your reply!
